services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: simplequeue
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

#  keycloak:
#    image: quay.io/keycloak/keycloak:24.0
#    command: start-dev
#    environment:
#      KC_BOOTSTRAP_ADMIN_USERNAME: admin
#      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
#    ports:
#      - "8080:8080"

#  ntfy:
#    image: binwiederhier/ntfy
#    command: serve
#    ports:
#      - "8081:80"
